[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# The verbosity level to use during tests.
verbosity = 3
solc_version = "0.8.20" 
evm_version = "london"
optimizer = true
optimizer_runs = 200

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = false

[rpc_endpoints]
# Commenting out for safety — none of the contracts in this repo are meant to be deployed to mainnet
# mainnet = "https://ethereum-rpc.publicnode.com"
# sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
base = "https://base-rpc.publicnode.com"
base-sepolia = "https://base-sepolia-rpc.publicnode.com"
arbitrum = "https://arbitrum-one-rpc.publicnode.com"
arbitrum-sepolia = "https://arbitrum-sepolia-rpc.publicnode.com"
optimism = "https://optimism-rpc.publicnode.com"
optimism-sepolia = "https://optimism-sepolia-rpc.publicnode.com"
scroll = "https://scroll-rpc.publicnode.com"
scroll-sepolia = "https://scroll-sepolia-rpc.publicnode.com"
linea = "https://linea-rpc.publicnode.com"
linea-sepolia = "https://linea-sepolia-rpc.publicnode.com"

[etherscan]
# Etherscan API keys are now universal, so we only need one
# https://docs.etherscan.io/contract-verification/supported-chains
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASE_API_KEY}" }
base-sepolia = { key = "${BASE_SEPOLIA_API_KEY}" }
arbitrum = { key = "${ARBITRUM_API_KEY}" }
arbitrum-sepolia = { key = "${ARBITRUM_SEPOLIA_API_KEY}" }
optimism = { key = "${OPTIMISM_API_KEY}" }
optimism-sepolia = { key = "${OPTIMISM_SEPOLIA_API_KEY}" }
scroll = { key = "${SCROLL_API_KEY}" }
scroll-sepolia = { key = "${SCROLL_SEPOLIA_API_KEY}" }
linea = { key = "${LINEA_API_KEY}" }
linea-sepolia = { key = "${LINEA_SEPOLIA_API_KEY}" }

[fuzz]
# The amount of fuzz runs to perform for each fuzz test case. 
# Higher values gives more confidence in results at the cost of testing speed.
runs = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
